### PR TITLE
 update gds admin ui readme file

### PR DESCRIPTION
**Pull request by elysee15**
Fixes SC-2921

### CODE REVIEW

**Review by pdeziel — CHANGES_REQUESTED** [review]
Thanks for making this change! While we're at it can we also fix the `TESTNET` misspelling that I mentioned in the story?

**Comment by elysee15** [comment]
> Thanks for making this change! While we're at it can we also fix the `TESTNET` misspelling that I mentioned in the story?

I fixed it in #302

**Comment by bbengfort** [comment]
@elysee15 does this PR need o be rebased or closed? It seems like the only change is whitespace.

**Comment by elysee15** [comment]
> @elysee15 does this PR need o be rebased or closed? It seems like the only change is whitespace.

**Pull request closed without merging**
